const { test } = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const init = require("../../cli/commands/init");
const { readState } = require("../../cli/lib/state");

const tmp = () => fs.mkdtempSync(path.join(os.tmpdir(), "nd-init-"));

test("init creates the full delivery tree", () => {
  const root = tmp();
  assert.strictEqual(init.run([], root, () => {}), 0);
  for (const rel of ["project.md", "AGENTS.md", "specs", "changes/archive",
                     "decisions", "ops/runbooks", "ops/postmortems",
                     ".adlc/state.json", ".adlc/waivers.md"]) {
    assert.ok(fs.existsSync(path.join(root, "delivery", rel)), `missing ${rel}`);
  }
});

test("init writes a valid initial state", () => {
  const root = tmp();
  init.run([], root, () => {});
  const s = JSON.parse(fs.readFileSync(path.join(root, "delivery", ".adlc", "state.json"), "utf8"));
  assert.strictEqual(s.version, 1);
  assert.strictEqual(s.change, null);
});

test("init refuses when delivery/ exists and leaves content untouched", () => {
  const root = tmp();
  fs.mkdirSync(path.join(root, "delivery"), { recursive: true });
  const sentinel = path.join(root, "delivery", "mine.md");
  fs.writeFileSync(sentinel, "do not touch");
  const lines = [];
  assert.strictEqual(init.run([], root, (s) => lines.push(s)), 1);
  assert.strictEqual(fs.readFileSync(sentinel, "utf8"), "do not touch");
  assert.ok(lines.join("\n").includes("already exists"));
  assert.ok(!fs.existsSync(path.join(root, "delivery", "project.md")));
});

// --- Controller ruling: verify templates BEFORE creating any directory ---

test("init with a missing template creates nothing and fails clearly", () => {
  const root = tmp();
  const templatesDir = path.join(__dirname, "..", "..", "templates", "delivery");
  const projectTemplate = path.join(templatesDir, "project.md");
  const movedAside = projectTemplate + ".test-moved-aside";
  // Rename rather than read+delete+rewrite: restoration doesn't depend on
  // faithfully round-tripping file content, only on the rename succeeding.
  fs.renameSync(projectTemplate, movedAside);
  try {
    const lines = [];
    const code = init.run([], root, (s) => lines.push(s));
    assert.strictEqual(code, 1);
    assert.ok(lines.join("\n").includes("project.md"), "error should name the missing template");
    assert.ok(!fs.existsSync(path.join(root, "delivery")), "delivery/ must not exist after a failed init");
  } finally {
    fs.renameSync(movedAside, projectTemplate);
  }
});

// --- Additional coverage beyond the brief ---

test("AGENTS.md is created and contains the generated-file marker", () => {
  const root = tmp();
  init.run([], root, () => {});
  const contents = fs.readFileSync(path.join(root, "delivery", "AGENTS.md"), "utf8");
  assert.ok(contents.includes("<!-- GENERATED by navi-delivery build_adapters -->"));
});

test(".adlc/waivers.md exists and contains the waiver table header", () => {
  const root = tmp();
  init.run([], root, () => {});
  const contents = fs.readFileSync(path.join(root, "delivery", ".adlc", "waivers.md"), "utf8");
  assert.ok(contents.includes("| Date | Change | Gate | Reason | Expires | Approved by |"));
});

test("the state written by init round-trips through readState() without throwing", () => {
  const root = tmp();
  init.run([], root, () => {});
  const s = readState(root);
  assert.deepStrictEqual(s, { version: 1, change: null, lane: null, phase: 1, gates: {}, stale: [] });
});
