"""Project the agent and skill tree into harness-specific adapters.

Generated output (never hand-edit any file this script writes):
  - adapters/claude-code/           Claude Code's expected plugin layout:
                                    agents/<name>.md (flat), skills/<name>/SKILL.md
                                    (discipline folded away), and its own
                                    .claude-plugin/plugin.json so the directory is a
                                    complete, installable plugin on its own — derived
                                    from the root manifest, never hand-written, so the
                                    two cannot drift apart.
  - adapters/generic/RUNBOOK.md     Paste-in protocol for a harness with no plugin
                                    support at all: the capability fallback table
                                    plus every agent and the skills it holds.
  - templates/delivery/AGENTS.md    The harness-agnostic entry point copied into a
                                    consuming repo by `navi-delivery init`.

Determinism: every input (frontmatter, registry/capabilities.json) is read and
iterated in a stable order (scripts.navi_lint.registry.load_entries sorts by
glob path; the capabilities registry is a JSON list, walked in file order), and
no output embeds a timestamp, PID, hash seed or absolute-path artefact that
would vary between two builds of the same tree. Building the same root twice
must produce byte-identical files.

Following this project's standing convention (see navi_lint/frontmatter.py and
validate_traceability.py): unreadable or malformed input is reported as a
readable message via BuildError / FrontmatterError, never as a bare traceback.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts.navi_lint.registry import Entry, load_entries
from scripts.navi_lint.frontmatter import FrontmatterError

BANNER = (
    "<!-- GENERATED by navi-delivery build_adapters -->\n"
    "<!-- Do not edit by hand: regenerate with `python3 scripts/build_adapters.py`. -->\n\n"
)


class BuildError(Exception):
    """A readable, non-traceback-worthy failure while building adapters."""


def _copy_banner(source_path: Path) -> str:
    return (
        f"<!-- GENERATED by navi-delivery build_adapters — do not edit; "
        f"source: {source_path.as_posix()} -->\n\n"
    )


def _bannered_copy(source_text: str, banner: str) -> str:
    """Insert `banner` right after the closing frontmatter delimiter (if any),
    so the file still begins with `---` for any harness that requires
    frontmatter to be the first bytes of the file."""
    text = source_text.replace("\r\n", "\n")
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end != -1:
            boundary = end + len("\n---\n")
            return text[:boundary] + banner + text[boundary:]
    return banner + text


def _load_capabilities(root: Path) -> list[dict]:
    path = root / "registry" / "capabilities.json"
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise BuildError(f"cannot read capability registry at {path}: {exc}") from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise BuildError(f"invalid JSON in capability registry {path}: {exc}") from exc
    if not isinstance(data, list):
        raise BuildError(f"capability registry {path} must be a JSON list of capabilities")
    return data


def _read_source(path: Path, context: str) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        raise BuildError(f"cannot read {path} while building {context}: {exc}") from exc


def _load_root_plugin_manifest(root: Path) -> dict:
    path = root / ".claude-plugin" / "plugin.json"
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise BuildError(f"cannot read plugin manifest at {path}: {exc}") from exc
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise BuildError(f"invalid JSON in plugin manifest {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise BuildError(f"plugin manifest {path} must be a JSON object")
    return data


def _build_claude_code_manifest(root_manifest: dict, cc_root: Path) -> Path:
    """Write adapters/claude-code/.claude-plugin/plugin.json, derived from the
    root manifest rather than hand-written, so the two cannot drift. JSON has
    no comment syntax, so the do-not-edit banner takes the form of a
    "_generated" key instead of an HTML comment. name/version are carried
    over verbatim — this adapter is never where a version bump belongs."""
    manifest: dict = {
        "_generated": (
            "GENERATED by navi-delivery build_adapters — do not edit by hand; "
            "derived from .claude-plugin/plugin.json at the repo root."
        )
    }
    manifest.update(root_manifest)
    target = cc_root / ".claude-plugin" / "plugin.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return target


def _build_claude_code(entries: list[Entry], cc_root: Path) -> list[Path]:
    """Flatten the discipline-nested source tree into Claude Code's expected
    plugin layout: agents/<name>.md (single file, not a directory) and
    skills/<name>/SKILL.md (discipline segment dropped)."""
    written: list[Path] = []
    for e in entries:
        source_text = _read_source(e.path, "the claude-code adapter")
        banner = _copy_banner(e.path)
        content = _bannered_copy(source_text, banner)
        if e.kind == "skill":
            target = cc_root / "skills" / e.name / "SKILL.md"
        elif e.kind == "agent":
            target = cc_root / "agents" / f"{e.name}.md"
        else:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(target)
    return written


def _capability_table_lines(capabilities: list[dict]) -> list[str]:
    lines = [
        "| Capability | claude_code | codex | cursor | Fallback when unavailable |\n",
        "|---|---|---|---|---|\n",
    ]
    for cap in capabilities:
        name = cap.get("name", "?")
        cc = cap.get("claude_code") or "—"
        cx = cap.get("codex") or "—"
        cu = cap.get("cursor") or "—"
        fb = cap.get("fallback") or "—"
        lines.append(f"| `{name}` | {cc} | {cx} | {cu} | {fb} |\n")
    return lines


def _agent_roster_lines(entries: list[Entry]) -> list[str]:
    lines: list[str] = []
    for e in entries:
        if e.kind != "agent":
            continue
        discipline = (e.meta.get("metadata") or {}).get("discipline", "?")
        skills = e.meta.get("skills") or []
        # owns_gates is empty for exactly one agent today (navi-agent-orchestrator,
        # which enforces gates while the owning persona records them) — join()
        # on an empty list is safe, but the message must say something sensible
        # rather than printing a blank "Owns gates: " line.
        gates = e.meta.get("owns_gates") or []
        gate_str = ", ".join(gates) if gates else "none (enforces gates without owning one)"
        description = (e.meta.get("description") or "").strip()
        first_line = description.splitlines()[0].strip() if description else ""
        lines.append(f"### {e.name} ({discipline})\n\n")
        if first_line:
            lines.append(f"{first_line}\n\n")
        lines.append(f"- Owns gates: {gate_str}\n")
        lines.append(f"- Skills: {', '.join(skills) if skills else 'none'}\n\n")
    return lines


def _build_generic_runbook(entries: list[Entry], capabilities: list[dict], generic_dir: Path) -> Path:
    generic_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        BANNER,
        "# navi-delivery — running with no plugin support\n\n",
        "Paste this file into the harness, then adopt each agent below in turn,\n",
        "loading the skills it lists before producing any artefact for that phase.\n",
        "Where a capability is not native to the harness, use its fallback.\n\n",
        "## Capability fallbacks\n\n",
    ]
    lines += _capability_table_lines(capabilities)
    lines.append("\n## Agents\n\n")
    lines += _agent_roster_lines(entries)
    path = generic_dir / "RUNBOOK.md"
    path.write_text("".join(lines), encoding="utf-8")
    return path


def _build_agents_md(entries: list[Entry], capabilities: list[dict], path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        BANNER,
        "# Working in this repo with navi-delivery\n\n",
        "This file is generated from the agent and skill tree so any harness — with\n",
        "or without plugin support — can pick up the framework from a single paste.\n",
        "Before producing any artefact, adopt the phase's agent below and load the\n",
        "skills it lists. If a listed capability is not native here, use its\n",
        "fallback instead.\n\n",
        "## Capability fallbacks\n\n",
    ]
    lines += _capability_table_lines(capabilities)
    lines.append("\n## Agents\n\n")
    lines += _agent_roster_lines(entries)
    path.write_text("".join(lines), encoding="utf-8")
    return path


def build(root: Path, out: Path) -> list[Path]:
    root = Path(root)
    out = Path(out)
    entries = load_entries(root)  # raises FrontmatterError with path/line/message, never a bare traceback
    capabilities = _load_capabilities(root)
    root_manifest = _load_root_plugin_manifest(root)

    cc_root = out / "claude-code"
    written: list[Path] = []
    written.extend(_build_claude_code(entries, cc_root))
    written.append(_build_claude_code_manifest(root_manifest, cc_root))
    written.append(_build_generic_runbook(entries, capabilities, out / "generic"))
    written.append(_build_agents_md(entries, capabilities, root / "templates" / "delivery" / "AGENTS.md"))
    return written


def main(argv: list[str]) -> int:
    root = Path(argv[0]) if argv else Path.cwd()
    try:
        written = build(root, root / "adapters")
    except FrontmatterError as exc:
        print(f"cannot build adapters: {exc}")
        return 1
    except BuildError as exc:
        print(f"cannot build adapters: {exc}")
        return 1
    print(f"wrote {len(written)} file(s)")
    for p in written:
        print(f"  {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
