"""Each agent ships a slash command, so an agent is reached the same way a skill
is. A skill has `/name`; an agent was prose-only ("use navi-agent-architect to
...") and nothing told a reader that. The command is generated from the agent's
own frontmatter so the skill list it recites cannot drift from the persona it
dispatches to.
"""
import json
import pathlib
import re
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[2]
ADAPTER = ROOT / "adapters" / "claude-code"
COMMANDS = ADAPTER / "commands"


def frontmatter(path: pathlib.Path) -> str:
    text = path.read_text(encoding="utf8")
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    return m.group(1) if m else ""


class AgentCommandTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.agents = sorted(p.stem for p in (ADAPTER / "agents").glob("navi-agent-*.md"))

    def test_every_agent_has_a_command_and_no_command_is_an_orphan(self):
        commands = sorted(p.stem for p in COMMANDS.glob("*.md"))
        self.assertEqual(commands, self.agents)

    def test_each_command_declares_what_a_slash_command_needs(self):
        for name in self.agents:
            fm = frontmatter(COMMANDS / f"{name}.md")
            self.assertIn("description:", fm, f"{name} command has no description")
            self.assertIn("argument-hint:", fm, f"{name} command has no argument hint")

    def test_each_command_passes_the_user_argument_through(self):
        """Without $ARGUMENTS the command silently drops whatever was typed after it."""
        for name in self.agents:
            self.assertIn("$ARGUMENTS", (COMMANDS / f"{name}.md").read_text(encoding="utf8"),
                          f"{name} command ignores its argument")

    def test_each_command_recites_exactly_its_agent_skills(self):
        """The list is generated from the agent file. A hand-kept copy would drift
        the first time a skill moved between agents."""
        for name in self.agents:
            agent = (ADAPTER / "agents" / f"{name}.md").read_text(encoding="utf8")
            block = re.search(r"^skills:\s*$\n((?:\s*-\s*\S+\s*\n)+)", agent, re.M)
            declared = re.findall(r"-\s*(\S+)", block.group(1)) if block else []
            cited = re.findall(r"^- `(navi-skill-[a-z-]+)`$",
                               (COMMANDS / f"{name}.md").read_text(encoding="utf8"), re.M)
            self.assertEqual(cited, declared, f"{name} command cites the wrong skills")

    def test_the_command_is_generated_not_hand_written(self):
        for name in self.agents:
            self.assertIn("GENERATED by navi-delivery build_adapters",
                          (COMMANDS / f"{name}.md").read_text(encoding="utf8"))

    def test_the_page_shows_the_slash_form_for_every_agent_and_skill(self):
        page = (ROOT / "docs" / "index.html").read_text(encoding="utf8")
        data = json.loads(re.search(
            r'<script id="navi-catalogue" type="application/json">(.*?)</script>',
            page, re.S).group(1))
        for item in data["agents"] + data["skills"]:
            invoke = item["readme"]["usage"]["invoke"]
            self.assertTrue(invoke, f'{item["name"]} has no invocation shown')
            self.assertTrue(any(i.startswith("/" + item["name"]) for i in invoke),
                            f'{item["name"]} does not show its own /name form')
            self.assertTrue(any(i.startswith("/navi-delivery:") for i in invoke),
                            f'{item["name"]} does not show the plugin-namespaced form')


if __name__ == "__main__":
    unittest.main()
