import json
import unittest
import tempfile
from pathlib import Path

from scripts.build_adapters import build, main

# NOTE: the task-16 brief's own fixture ("description: Use when x. Trigger
# phrases include: a.") is invalid YAML — an unquoted plain scalar cannot
# contain ": " (PyYAML raises "mapping values are not allowed here"), which
# is exactly the kind of stale-brief bug the task calls out. Every real
# SKILL.md/agent.md in this repo instead uses a `>` folded block scalar for
# `description`, so these fixtures follow that real convention.
SKILL = (
    "---\nname: navi-skill-alpha\ndescription: >\n  Use when x.\n  Trigger phrases include: a.\n"
    "allowed-tools: Read\nmetadata:\n  kind: skill\n  discipline: architecture\n---\nbody\n"
)
AGENT = (
    "---\nname: navi-agent-architect\ndescription: >\n  Use when designing.\nallowed-tools: Read\n"
    "metadata:\n  kind: agent\n  discipline: architecture\nowns_gates: [G3]\n"
    "skills: [navi-skill-alpha]\n---\nbody\n"
)
# The one carried constraint this project has repeatedly warned about: exactly
# one real agent (navi-agent-orchestrator) has owns_gates: [] and a naive
# generator (e.g. one that indexes owns_gates[0]) crashes on it.
AGENT_NO_GATES = (
    "---\nname: navi-agent-orchestrator\ndescription: >\n  Use when routing.\nallowed-tools: Read\n"
    "metadata:\n  kind: agent\n  discipline: lifecycle-method\nowns_gates: []\n"
    "skills: [navi-skill-alpha]\n---\nbody\n"
)

CAPABILITIES = [
    {"name": "read_file", "claude_code": "Read", "codex": "file read", "cursor": "file read",
     "fallback": "ask the human to paste the file"},
    {"name": "write_file", "claude_code": "Write", "codex": "file write", "cursor": "file write",
     "fallback": "emit the file in a fenced block"},
    {"name": "run_command", "claude_code": "Bash", "codex": "shell", "cursor": "shell",
     "fallback": "ask the human to run it and paste output"},
    {"name": "search", "claude_code": "Grep/Glob", "codex": "search", "cursor": "search",
     "fallback": "ask for the relevant paths"},
    {"name": "ask_human", "claude_code": "AskUserQuestion", "codex": "prompt", "cursor": "prompt",
     "fallback": "ask a plain question, then wait"},
    {"name": "spawn_subagent", "claude_code": "Agent", "codex": None, "cursor": None,
     "fallback": "adopt the persona sequentially in this session"},
]


def tree(t, include_orchestrator=False):
    root = Path(t)
    sd = root / "skills" / "architecture" / "navi-skill-alpha"
    sd.mkdir(parents=True)
    (sd / "SKILL.md").write_text(SKILL, encoding="utf-8")

    ad = root / "agents" / "navi-agent-architect"
    ad.mkdir(parents=True)
    (ad / "navi-agent-architect.agent.md").write_text(AGENT, encoding="utf-8")

    if include_orchestrator:
        od = root / "agents" / "navi-agent-orchestrator"
        od.mkdir(parents=True)
        (od / "navi-agent-orchestrator.agent.md").write_text(AGENT_NO_GATES, encoding="utf-8")

    reg = root / "registry"
    reg.mkdir(parents=True)
    (reg / "capabilities.json").write_text(json.dumps(CAPABILITIES), encoding="utf-8")

    (root / "templates" / "delivery").mkdir(parents=True)
    (root / "templates" / "delivery" / "AGENTS.md").write_text(
        "<!-- GENERATED by navi-delivery build_adapters -->\n\nstub\n", encoding="utf-8"
    )
    return root


class TestBuildAdapters(unittest.TestCase):
    def test_writes_claude_code_flat_layout_and_generic_runbook(self):
        with tempfile.TemporaryDirectory() as t:
            root = tree(t)
            written = build(root, root / "adapters")
            names = {p.name for p in written}
            self.assertIn("RUNBOOK.md", names)
            self.assertTrue(
                (root / "adapters" / "claude-code" / "skills" / "navi-skill-alpha" / "SKILL.md").exists()
            )
            # Agents are a single flat file in Claude Code's layout, not a
            # directory carrying the source's .agent.md name.
            self.assertTrue(
                (root / "adapters" / "claude-code" / "agents" / "navi-agent-architect.md").exists()
            )

    def test_writes_agents_md_with_marker_preserved(self):
        with tempfile.TemporaryDirectory() as t:
            root = tree(t)
            written = build(root, root / "adapters")
            agents_md = root / "templates" / "delivery" / "AGENTS.md"
            self.assertIn(agents_md, written)
            text = agents_md.read_text(encoding="utf-8")
            self.assertIn("<!-- GENERATED by navi-delivery build_adapters -->", text)
            self.assertIn("navi-agent-architect", text)

    def test_runbook_lists_every_capability_with_its_fallback(self):
        with tempfile.TemporaryDirectory() as t:
            root = tree(t)
            build(root, root / "adapters")
            text = (root / "adapters" / "generic" / "RUNBOOK.md").read_text(encoding="utf-8")
            for cap in CAPABILITIES:
                self.assertIn(cap["name"], text)
                self.assertIn(cap["fallback"], text)

    def test_generated_md_files_carry_the_do_not_edit_banner(self):
        with tempfile.TemporaryDirectory() as t:
            root = tree(t)
            for p in build(root, root / "adapters"):
                if p.suffix == ".md":
                    self.assertIn("GENERATED", p.read_text(encoding="utf-8"))

    def test_agent_with_empty_owns_gates_does_not_crash(self):
        with tempfile.TemporaryDirectory() as t:
            root = tree(t, include_orchestrator=True)
            written = build(root, root / "adapters")
            self.assertTrue(
                (root / "adapters" / "claude-code" / "agents" / "navi-agent-orchestrator.md").exists()
            )
            runbook = next(p for p in written if p.name == "RUNBOOK.md")
            text = runbook.read_text(encoding="utf-8")
            self.assertIn("navi-agent-orchestrator", text)
            self.assertIn("none (enforces gates without owning one)", text)

    def test_copied_frontmatter_still_starts_the_file(self):
        with tempfile.TemporaryDirectory() as t:
            root = tree(t)
            build(root, root / "adapters")
            skill_copy = root / "adapters" / "claude-code" / "skills" / "navi-skill-alpha" / "SKILL.md"
            self.assertTrue(skill_copy.read_text(encoding="utf-8").startswith("---\n"))

    def test_determinism_same_input_byte_identical_output(self):
        with tempfile.TemporaryDirectory() as t:
            root = tree(t, include_orchestrator=True)
            build(root, root / "adapters" / "run1")
            build(root, root / "adapters" / "run2")
            for p1 in sorted((root / "adapters" / "run1").rglob("*")):
                if p1.is_dir():
                    continue
                rel = p1.relative_to(root / "adapters" / "run1")
                p2 = root / "adapters" / "run2" / rel
                self.assertEqual(p1.read_bytes(), p2.read_bytes(), f"mismatch at {rel}")

    def test_main_returns_zero_and_reports_files(self):
        with tempfile.TemporaryDirectory() as t:
            root = tree(t)
            rc = main([str(root)])
            self.assertEqual(rc, 0)

    def test_main_reports_readable_message_not_traceback_on_bad_capabilities_json(self):
        with tempfile.TemporaryDirectory() as t:
            root = tree(t)
            (root / "registry" / "capabilities.json").write_text("{not json", encoding="utf-8")
            rc = main([str(root)])
            self.assertEqual(rc, 1)


if __name__ == "__main__":
    unittest.main()
